"""Automated state file generator — the 'RAM' engine.

Collects Git state (branch, commits, diffs) and directory structure, then
renders a token-budgeted markdown state file that gives AI agents instant
context about the current repository state.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from jinja2 import Template

from comcan.config import load_config
from comcan.context_budget import ContextBudget
from comcan.file_parser import generate_tree
from comcan.git_utils import (
    get_changed_files,
    get_current_branch,
    get_diff_summary,
    get_recent_commits,
    get_repo_root,
    GitError,
)
from comcan.security import sanitize_content, validate_write_path


# ── State Template ──────────────────────────────────────────────────────────

_STATE_TEMPLATE = Template("""\
# Codebase Context — Auto-generated by ComCan
> **Do not edit manually.** This file is regenerated on every commit and branch switch.

**Branch:** `{{ branch }}`  |  **Updated:** {{ timestamp }}

## Recent Commits
```text
{{ commits }}
```

{% if changed_files %}
## Changed Files (vs `{{ base_branch }}`)
```text
{{ changed_files }}
```
{% endif %}

{% if diff_summary %}
## Diff Summary
```text
{{ diff_summary }}
```
{% endif %}

## Directory Structure
```text
{{ tree }}
```
""")


def generate_state(
    repo_root: Path,
    budget_profile: str = "large",
    base_branch: str = "main",
    extra_ignores: Optional[list[str]] = None,
    secret_patterns: Optional[list[str]] = None,
) -> str:
    """Generate the state markdown content.

    Collects Git information and directory tree, sanitizes secrets,
    and fits everything within the token budget.

    Args:
        repo_root: Git repository root directory.
        budget_profile: Context budget profile name.
        base_branch: Branch to compare diffs against.
        extra_ignores: Additional file patterns to exclude from tree.
        secret_patterns: Additional secret patterns to strip.

    Returns:
        Rendered markdown string.
    """
    budget = ContextBudget(budget_profile)
    allocations = budget.allocate()

    # ── Gather raw data ─────────────────────────────────────────────────

    try:
        branch = get_current_branch(cwd=repo_root)
    except GitError:
        branch = "unknown"

    try:
        raw_commits = get_recent_commits(n=10, cwd=repo_root)
    except GitError:
        raw_commits = "(no commits yet)"

    try:
        raw_changed = get_changed_files(ref=base_branch, cwd=repo_root)
    except GitError:
        raw_changed = ""

    try:
        raw_diff = get_diff_summary(ref=base_branch, cwd=repo_root)
    except GitError:
        raw_diff = ""

    raw_tree = generate_tree(
        root=repo_root,
        max_depth=4,
        token_budget=allocations.get("tree", 4000),
        extra_ignores=extra_ignores,
    )

    # ── Sanitize secrets ────────────────────────────────────────────────

    commits = sanitize_content(raw_commits, secret_patterns)
    changed_files = sanitize_content(raw_changed, secret_patterns)
    diff_summary = sanitize_content(raw_diff, secret_patterns)
    tree = raw_tree  # Tree is just filenames, no secrets

    # ── Fit to budget ───────────────────────────────────────────────────

    sections = budget.fit_content({
        "tree": tree,
        "commits": commits,
        "diff": diff_summary,
    })

    # ── Render template ─────────────────────────────────────────────────

    return _STATE_TEMPLATE.render(
        branch=branch,
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        base_branch=base_branch,
        commits=sections.get("commits", commits),
        changed_files=changed_files,
        diff_summary=sections.get("diff", diff_summary),
        tree=sections.get("tree", tree),
    )


def write_state(
    repo_root: Optional[Path] = None,
    **kwargs,
) -> Path:
    """Generate and write the state file to disk.

    Args:
        repo_root: Git repository root (auto-detected if None).
        **kwargs: Passed to ``generate_state()``.

    Returns:
        Path to the written state file.
    """
    if repo_root is None:
        repo_root = get_repo_root()

    # Load config for overrides
    config = load_config(repo_root)

    # Apply config defaults (kwargs take precedence)
    effective_kwargs = {
        "budget_profile": config.budget_profile,
        "base_branch": config.base_branch,
        "extra_ignores": config.extra_ignores,
        "secret_patterns": config.secret_patterns,
    }
    effective_kwargs.update(kwargs)

    content = generate_state(repo_root, **effective_kwargs)

    state_path = repo_root / ".comcan" / "CURRENT_STATE.md"
    validate_write_path(state_path, repo_root)
    state_path.parent.mkdir(parents=True, exist_ok=True)

    state_path.write_text(content, encoding="utf-8")
    return state_path
